### ISSUE TITLE
Add a list with icon packs using Blueprint

### ISSUE THREAD

**Issue by braniii** [jahirfiquitiva/Blueprint#180]
I'm planning to design an icon pack and was wondering if I should use Blueprint. To convince people to use your Dashboard, I think it would be helpful to see it in action. So just add in the readme file a section with icon packs which are using your dashboard Blueprint.

**Comment by jahirfiquitiva** [comment]
I won't do it because I don't want to bloat the `README` with that, anyways, this gave me an idea, and I will create a special file to list some apps, as a reward for those who become [sponsors](https://github.com/users/jahirfiquitiva/sponsorship).

Anyways, here's a quick search in Google Play Store that mention my name somewhere and are likely using any of my 3 dashboards (Blueprint, Frames or Kuper).
https://play.google.com/store/search?q=Jahir%20Fiquitiva&c=apps
