### ISSUE TITLE
 Request for custom icon name

### ISSUE THREAD

**Issue by anarchist22** [jahirfiquitiva/Blueprint#304]
### Blueprint Version

2.3.4

### Describe the feature

The icons take the name of the drawable, I wish I could add a custom name so I could better sort each icon. I leave an example : 
![Screenshot_20230301-140016_APK Editor](https://user-images.githubusercontent.com/71122765/222240412-2b071a66-01f8-4063-8f95-23e5c66dc84f.jpg)

This is how the drawable and the custom name are displayed, in such a way I can put a custom name and the name to be displayed. 
![Screenshot_20230301-140053_Acons YOU](https://user-images.githubusercontent.com/71122765/222240846-f9e84733-c325-4de7-8cd3-acd2936a7d62.jpg)

AccuWeather with the current version it is displayed as: Accuweather, with the new features it would be displayed with the name of the application and not the drawable. 

This feature would help each icon to be renamed with the name of the application respecting numbers, capital letters and other characters.

**Comment by jahirfiquitiva** [comment]
You can already achieve this by naming your icon files following this convention:
https://github.com/jahirfiquitiva/Blueprint/wiki/Setting-up-icon-pack-(Part-2)#naming-icons

**Comment by anarchist22** [comment]
The way of naming the files is interesting, but why not make it easier like in CandyBar where I took the examples from? It is much more intuitive and easy regardless of what the icon file name is.

**Comment by jahirfiquitiva** [comment]
Because there's another file where icons are listed: `icon_pack.xml` which some launchers (I can't tell exactly which ones specifically) use to display icons in their icon selector and maybe other places.

In that file, the icon/app name cannot be specified in the same way it can be done in `drawable.xml`.

I can understand the Blueprint way would require some work coming from another dashboard, but it's much easier when you start with it, as you would only need to define the icon file name and not both.
